# Configs
---
output_name: drive_explicacao.mp4
inputs:
  - input:
      file: drives.mp4
      complete: True
      volume : 1
  - input:
      file: explicacaomarcelo.mp4
      complete: True
      volume : 1
  - input:
      file: drive_forte.mp4
      complete: True
      volume : 1


